// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoqggyuokswobgnftnxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvcWdneXVva3N3b2JnbmZ0bnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTk3OTMsImV4cCI6MjA3MTEzNTc5M30.SJ6uoYqm7AGprxMtPmuDyqoHOeT5cUA9bA0hXxAraVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});